public with sharing class Constants {
    public static final String INITIAL_PAYMENT = 'Initial Payment';
    public static final String SECURITY_DEPOSIT = 'Security Deposit';
    public static final String PARTIAL_PAYMENT = 'Partial Payment';
    public static final String TRANSACTION_SUCCESS_STATUS = 'Success';
    public static final String BOOKING_PAID = 'Paid';
    public static final String BOOKING_PARTIAL_PAID = 'Partially Paid';
    public static final String BOOKING_PENDING = 'Pending';
    public static final String BOOKING_CANCELLED_STATUS = 'Cancelled';
    public static final String BOOKING_CONFIRMED_STATUS = 'Confirmed';
}