public with sharing class Constants {
    public static final String INITIAL_PAYMENT = 'Initial Payment';
    public static final String SECURITY_DEPOSIT = 'Security Deposit';
    public static final String PARTIAL_PAYMENT = 'Partial Payment';
    public static final String TRANSACTION_SUCCESS_STATUS = 'Success';
    public static final String BOOKING_PAID = 'Paid';
    public static final String BOOKING_PARTIAL_PAID = 'Partially Paid';
    public static final String BOOKING_PENDING = 'Pending';
    public static final String BOOKING_CANCELLED_STATUS = 'Cancelled';
    public static final String BOOKING_CONFIRMED_STATUS = 'Confirmed';
    public static final String BOOKING_CLOSED_STATUS = 'Closed';
    public static final Integer LOW_RATING_THRESHOLD = 3;
    public static final Integer DEFAULT_RATING_THRESHOLD = 5;
    public static final String CUSTOMER_SUPPORT_PUBLIC_GROUP = 'Customer_Support_Review_Group';
    public static final String SHARING_WITH_READ_ACCESS = 'Read';
    public static final String CASE_RECORD_TYPE_REVIEW_ISSUE = 'Review_Issue';
    public static final String CASE_TYPE_NEGATIVE_REVIEW = 'Negative Review';
    public static final String CASE_PRIORITY_MEDIUM = 'Medium';
}